### ISSUE TITLE
Issues about the Glasgow Coma Scale (GCS) Score in SICDB v1.0.6

### ISSUE THREAD

**Issue by weilidr** [nrodemund/sicdb#6]
Dear Administrators of the SICdb,

I have successfully deployed SICdb V1.0.6,  a pivotal resource that will markedly propel the field of intensive care medicine forward. Recently, I have been exploring the SICdb V1.0.6 database, SICdb is among the largest ICU datasets currently available worldwide and has high granularity data for vital signs, laboratory tests, and more. However, I have noticed that the database appears to be missing the GCS score. The GCS score is a fundamental component in evaluating the consciousness level of ICU patients and is essential for calculating critical care scores such as SOFA, APACHE, and SAPS. I wonder if future versions will include the GCS score.

Additionally, I have noticed multiple references to version 1.0.7 on the project website and in various GitHub Issues. However, the latest version available on PhysioNet is v1.0.6. I wonder whether v1.0.7 has been released or if it is still under development. 

Thank you for your time and attention to this matter. 

best regards

**Comment by huangzhuohua** [comment]
@weilidr Did you use RooDataServer software when installing and generating data? I have searched the SICDB website and documents many times, but I couldn't find the download address of RooDataServer.

**Comment by nrodemund** [comment]
@weilidr GCS is included in 1.0.7 / 1.0.8 which is in review since some months on PhysioNet ( -.- ) Unfortunately it won't help you in a scientific way because it is not mandatory on our icu and therefore not valid enough. Additionally sometimes someone gives a low GCS for deeply sedated patients.

@huangzhuohua Better use the csv files. I still use this software for every study that uses aggregated data, but the public version has been discontinued due to low interest and high support expense. I'll update the docs about that...

To build up a database posgres/mysql/sqlite you may use the python script provided https://github.com/nrodemund/sicdb/tree/main/Import/Python
